table Geolocation
	lineageTag: fe3fef57-aab6-4a76-b7bc-84efc7ab08db

	column ZipCodePrefix
		dataType: int64
		formatString: 0
		lineageTag: 05164415-339a-4962-9a4e-78dfb48baa80
		summarizeBy: sum
		sourceColumn: ZipCodePrefix

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 420e3a29-1714-482e-a416-c3f66cb7db2e
		summarizeBy: sum
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 6404814a-8ae3-44a1-b603-08760b90cd00
		summarizeBy: sum
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GeoCity
		dataType: string
		lineageTag: 4c0f6a15-bc11-4930-b530-a4be0acda60d
		summarizeBy: none
		sourceColumn: GeoCity

		annotation SummarizationSetBy = Automatic

	column GeoState
		dataType: string
		lineageTag: db838226-2d7d-4c03-ae7f-e03118f936f1
		summarizeBy: none
		sourceColumn: GeoState

		annotation SummarizationSetBy = Automatic

	partition Geolocation = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents("C:\Users\iamaa\Downloads\olist-ai-powerbi\data\raw\olist_geolocation_dataset.csv"),
				        [Delimiter = ",", Columns = 5, QuoteStyle = QuoteStyle.None]
				    ),
				
				    #"Promoted Headers" = Table.PromoteHeaders(
				        Source,
				        [PromoteAllScalars = true]
				    ),
				
				    #"Changed Column Types" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"geolocation_zip_code_prefix", Int64.Type},
				            {"geolocation_lat", type number},
				            {"geolocation_lng", type number},
				            {"geolocation_city", type text},
				            {"geolocation_state", type text}
				        },
				        "en-US"
				    ),
				
				    #"Renamed Columns" = Table.RenameColumns(
				        #"Changed Column Types",
				        {
				            {"geolocation_zip_code_prefix", "ZipCodePrefix"},
				            {"geolocation_lat", "Latitude"},
				            {"geolocation_lng", "Longitude"},
				            {"geolocation_city", "GeoCity"},
				            {"geolocation_state", "GeoState"}
				        }
				    )
				
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

