table Products
	lineageTag: a4cd2d4e-6688-4f48-ac18-0b19811ef43b

	column ProductID
		dataType: string
		lineageTag: 28a3b580-c5f3-466e-b133-20d34125edd2
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductCategory
		dataType: string
		lineageTag: 1e7cfe26-f805-461a-9912-de1fed496fc3
		summarizeBy: none
		sourceColumn: ProductCategory

		annotation SummarizationSetBy = Automatic

	column ProductNameLength
		dataType: int64
		formatString: 0
		lineageTag: fda93b59-2258-46d3-ae73-2e6896852da3
		summarizeBy: none
		sourceColumn: ProductNameLength

		annotation SummarizationSetBy = Automatic

	column ProductDescriptionLength
		dataType: int64
		formatString: 0
		lineageTag: 33d6639d-5f8a-4e3d-8094-dc9706941cbb
		summarizeBy: none
		sourceColumn: ProductDescriptionLength

		annotation SummarizationSetBy = Automatic

	column ProductPhotosQty
		dataType: int64
		formatString: 0
		lineageTag: d44fc974-7390-475b-93fb-59290099adb2
		summarizeBy: none
		sourceColumn: ProductPhotosQty

		annotation SummarizationSetBy = Automatic

	column ProductWeightGrams
		dataType: int64
		formatString: 0
		lineageTag: 5fbee9be-e888-453c-99eb-7e80a92a8304
		summarizeBy: none
		sourceColumn: ProductWeightGrams

		annotation SummarizationSetBy = Automatic

	column ProductLengthCm
		dataType: int64
		formatString: 0
		lineageTag: 528ff1aa-7c5a-4ca0-8148-8577753c70fd
		summarizeBy: none
		sourceColumn: ProductLengthCm

		annotation SummarizationSetBy = Automatic

	column ProductHeightCm
		dataType: int64
		formatString: 0
		lineageTag: 2766427a-ceee-45cc-afc7-cc672e93011a
		summarizeBy: none
		sourceColumn: ProductHeightCm

		annotation SummarizationSetBy = Automatic

	column ProductWidthCm
		dataType: int64
		formatString: 0
		lineageTag: 231931d6-3c40-4860-9c65-1f153a12f4a7
		summarizeBy: none
		sourceColumn: ProductWidthCm

		annotation SummarizationSetBy = Automatic

	column ProductVolumeCm3
		dataType: double
		lineageTag: 8925c517-eaf4-4b25-b4fa-7f79f9421c8a
		summarizeBy: none
		sourceColumn: ProductVolumeCm3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Products = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents("C:\Users\iamaa\Downloads\olist-ai-powerbi\data\raw\olist_products_dataset.csv"),
				        [Delimiter = ",", Columns = 9, QuoteStyle = QuoteStyle.None]
				    ),
				
				    #"Promoted Headers" = Table.PromoteHeaders(
				        Source,
				        [PromoteAllScalars = true]
				    ),
				
				    #"Changed Column Types" = Table.TransformColumnTypes(
				        #"Promoted Headers",
				        {
				            {"product_id", type text},
				            {"product_category_name", type text},
				            {"product_name_lenght", Int64.Type},
				            {"product_description_lenght", Int64.Type},
				            {"product_photos_qty", Int64.Type},
				            {"product_weight_g", Int64.Type},
				            {"product_length_cm", Int64.Type},
				            {"product_height_cm", Int64.Type},
				            {"product_width_cm", Int64.Type}
				        },
				        "en-US"
				    ),
				
				    #"Renamed Columns" = Table.RenameColumns(
				        #"Changed Column Types",
				        {
				            {"product_id", "ProductID"},
				            {"product_category_name", "ProductCategory"},
				            {"product_name_lenght", "ProductNameLength"},
				            {"product_description_lenght", "ProductDescriptionLength"},
				            {"product_photos_qty", "ProductPhotosQty"},
				            {"product_weight_g", "ProductWeightGrams"},
				            {"product_length_cm", "ProductLengthCm"},
				            {"product_height_cm", "ProductHeightCm"},
				            {"product_width_cm", "ProductWidthCm"}
				        }
				    ),
				
				    #"Added Product Volume" = Table.AddColumn(
				        #"Renamed Columns",
				        "ProductVolumeCm3",
				        each
				            if [ProductLengthCm] = null
				                or [ProductHeightCm] = null
				                or [ProductWidthCm] = null
				            then
				                null
				            else
				                [ProductLengthCm] * [ProductHeightCm] * [ProductWidthCm],
				        type number
				    )
				
				in
				    #"Added Product Volume"

	annotation PBI_ResultType = Table

